# Generated by Django 2.1.4 on 2018-12-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution Name')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('category', models.CharField(blank=True, choices=[('1', 'Stated Owned Bank'), ('2', 'Regional Bank'), ('3', 'Private Forex Bank'), ('4', 'Private Non-Forex Bank'), ('5', 'Joint Venture Bank'), ('6', 'Foreign Bank')], max_length=1, null=True)),
            ],
        ),
    ]
